# STAGE 1 - IMPORTS AND CONFIGURATION

In [6]:
import os
import time
import asyncio
import logging
import numpy as np
import pandas as pd
import nltk
import instructor

from dotenv import load_dotenv
from openai import AsyncOpenAI

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_core.prompts import ChatPromptTemplate

from bert_score import BERTScorer
from rouge_score import rouge_scorer
from nltk.translate.meteor_score import meteor_score

from ragas.embeddings import OpenAIEmbeddings as RagasEmbeddings
from ragas.llms import InstructorLLM
from ragas.metrics.collections import AnswerCorrectness

from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from deepeval.metrics import (
    GEval,
    AnswerRelevancyMetric,
    ContextualPrecisionMetric,
    ContextualRecallMetric,
    FaithfulnessMetric
)

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY not found in .env")

logging.getLogger("deepeval").setLevel(logging.CRITICAL)
logging.getLogger("transformers").setLevel(logging.ERROR)

nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)

INPUT_CSV = "ai_teacher_20_questions.csv"
PDF_FILE = "HopeAI_Teaching.pdf"
OUTPUT_CSV = "RAG_LLM_FINAL_EVALUATION.csv"

MODEL = "gpt-4o-mini"
EVALUATION_MODEL = "gpt-4.1"

# Configure these according to the current API pricing.
INPUT_PRICE = 0.15 / 1_000_000
OUTPUT_PRICE = 0.60 / 1_000_000

df = pd.read_csv(INPUT_CSV)

required_columns = ["User Query", "Teacher Response"]
missing = set(required_columns) - set(df.columns)

if missing:
    raise ValueError(f"Missing CSV columns: {missing}")

df = df.dropna(subset=required_columns).reset_index(drop=True)

df["User Query"] = df["User Query"].astype(str).str.strip()
df["Teacher Response"] = df["Teacher Response"].astype(str).str.strip()

print(f"Questions loaded: {len(df)}")

Questions loaded: 20

C:\Users\User\AppData\Local\Temp\ipykernel_35500\1418208404.py:27: DeprecationWarning: 'LLMTestCaseParams' is deprecated and will be removed in a future release. Use 'SingleTurnParams' instead.
  from deepeval.test_case import LLMTestCase, LLMTestCaseParams

# STAGE 2 - RAG PIPELINE

In [7]:
# LOAD PDF
documents = PyPDFLoader(PDF_FILE).load()

# CHUNK DOCUMENTS
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=150)
chunks = text_splitter.split_documents(documents)

# CREATE FAISS VECTOR STORE
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")
vectorstore = FAISS.from_documents(chunks, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

# LLM
gpt_model = ChatOpenAI(model=MODEL, temperature=0, timeout=120, max_retries=3)

# RAG PROMPT

rag_prompt = ChatPromptTemplate.from_template("""
Answer the question using only the retrieved context.

If the answer is not available in the context,
say that the information could not be found in the documents.

Context:
{context}

Question:
{question}

Answer:
""")

# RETRIEVE CONTEXT

def get_context(query):
    retrieved_docs = retriever.invoke(query)
    retrieval_context = [
        doc.page_content for doc in retrieved_docs
    ]
    context = "\n\n".join(retrieval_context)
    return context, retrieval_context

print("PDF pages loaded:", len(documents))
print("Chunks created:", len(chunks))
print("FAISS vector store and top-3 retriever ready.")

PDF pages loaded: 6
Chunks created: 18
FAISS vector store and top-3 retriever ready.

# STAGE 3 - DEFINE EVALUATION METRICS

In [8]:
# SIMILARITY METRICS

bert_scorer = BERTScorer(lang="en", rescale_with_baseline=False)
rouge = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

# ANSWER QUALITY METRICS
correctness_metric = GEval(
    name="Answer Correctness",
    model=EVALUATION_MODEL,
    criteria="""
    Compare the generated answer with the reference answer.
    Evaluate factual accuracy, important information,
    and contradictions. Ignore minor wording differences.
    """,
    evaluation_params=[
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT
    ],
    async_mode=False
)

helpfulness_metric = GEval(
    name="Helpfulness",
    model=EVALUATION_MODEL,
    criteria="""
    Evaluate whether the answer directly addresses the question,
    is easy for a beginner to understand, and gives a clear,
    useful explanation without unnecessary information.
    """,
    evaluation_params=[
        LLMTestCaseParams.INPUT,
        LLMTestCaseParams.ACTUAL_OUTPUT
    ],
    async_mode=False
)
answer_relevancy_metric = AnswerRelevancyMetric(model=EVALUATION_MODEL, include_reason=False, async_mode=False)

# RAGAS ANSWER CORRECTNESS
ragas_client = AsyncOpenAI(api_key=api_key)
instructor_client = instructor.from_openai(ragas_client)
ragas_llm = InstructorLLM(
    client=instructor_client,
    model="gpt-5-nano",
    provider="openai",
    max_tokens=8192,
    temperature=1.0
)
ragas_embedding_client = AsyncOpenAI(api_key=api_key)
ragas_embedding_model = RagasEmbeddings(client=ragas_embedding_client, model="text-embedding-3-small")
answer_correctness_metric = AnswerCorrectness(llm=ragas_llm, embeddings=ragas_embedding_model)

# RAG GEVAL
rag_geval_metric = GEval(
    name="RAG Correctness",
    model="gpt-5-nano",
    criteria="""
    Evaluate whether the generated answer is factually correct
    and consistent with the reference answer.
    """,
    evaluation_params=[
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT
    ],
    async_mode=False
)

# RETRIEVAL / RAG METRICS
context_precision_metric = ContextualPrecisionMetric(model=EVALUATION_MODEL)
context_recall_metric = ContextualRecallMetric(model=EVALUATION_MODEL)
faithfulness_metric = FaithfulnessMetric(model=EVALUATION_MODEL)
rag_answer_relevancy_metric = AnswerRelevancyMetric(model=EVALUATION_MODEL, include_reason=False, async_mode=False)
print("All evaluation metrics initialized.")

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

All evaluation metrics initialized.

# STAGE 4 - INPUT QUERIES, GENERATE ANSWERS AND CALCULATE OPERATIONAL METRICS

In [23]:
from tqdm.auto import tqdm

results = []

for _, row in tqdm(
    df.iterrows(),
    total=len(df),
    desc="RAG generation"
):
    query = row["User Query"]
    reference = row["Teacher Response"]

    try:
        total_start = time.perf_counter()

        # RETRIEVAL
        start = time.perf_counter()
        context, retrieval_context = get_context(query)
        retrieval_latency = time.perf_counter() - start

        # GENERATION
        prompt_value = rag_prompt.invoke({
            "context": context,
            "question": query
        })

        start = time.perf_counter()
        response = gpt_model.invoke(prompt_value)
        generation_latency = time.perf_counter() - start

        total_latency = time.perf_counter() - total_start

        generated = response.content.strip()

        # TOKEN USAGE
        metadata = getattr(response, "response_metadata", {})
        usage = metadata.get("token_usage", {})

        input_tokens = usage.get("prompt_tokens", 0)
        output_tokens = usage.get("completion_tokens", 0)
        total_tokens = usage.get(
            "total_tokens",
            input_tokens + output_tokens
        )

        # COST
        input_cost = input_tokens * INPUT_PRICE
        output_cost = output_tokens * OUTPUT_PRICE
        total_cost = input_cost + output_cost

        results.append({
            "User Query": query,
            "Teacher Response": reference,
            "GeneratedAnswer": generated,
            "RetrievedContext": retrieval_context,

            "RetrievalLatency": retrieval_latency,
            "GenerationLatency": generation_latency,
            "Latency": total_latency,

            "InputTokens": input_tokens,
            "OutputTokens": output_tokens,
            "TotalTokens": total_tokens,

            "InputCost": input_cost,
            "OutputCost": output_cost,
            "TotalCost": total_cost
        })

    except Exception as e:
        print(f"\nError: {query}\n{e}")

        results.append({
            "User Query": query,
            "Teacher Response": reference,
            "GeneratedAnswer": "",
            "RetrievedContext": [],

            "RetrievalLatency": np.nan,
            "GenerationLatency": np.nan,
            "Latency": np.nan,

            "InputTokens": np.nan,
            "OutputTokens": np.nan,
            "TotalTokens": np.nan,

            "InputCost": np.nan,
            "OutputCost": np.nan,
            "TotalCost": np.nan
        })


results_df = pd.DataFrame(results)

display(results_df)

ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-2784' coro=<_async_in_context.<locals>.run_in_context() done, defined at C:\Users\User\anaconda3\envs\ai\Lib\site-packages\ipykernel\utils.py:57> wait_for=<Task pending name='Task-2785' coro=<Kernel.shell_main() running at C:\Users\User\anaconda3\envs\ai\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at C:\Users\User\anaconda3\envs\ai\Lib\site-packages\zmq\eventloop\zmqstream.py:564]>
Exception ignored in: <coroutine object Kernel.shell_main at 0x000002158B32F740>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
Exception ignored in: <coroutine object Kernel.shell_main at 0x000002158B32F740>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
KeyError: '__import__'
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-2785' coro=<Kernel.shell_main() running at C:\Users\User\anaconda3\envs\ai\Lib\site-packages\ipykernel\kernelbase.py:597> cb=[Task.__wakeup()]>

RAG generation:   0%|          | 0/20 [00:00<?, ?it/s]

,User Query,Teacher Response,GeneratedAnswer,RetrievedContext,RetrievalLatency,GenerationLatency,Latency,InputTokens,OutputTokens,TotalTokens,InputCost,OutputCost,TotalCost
0,What is AI?,AI (Artificial Intelligence) is the ability of...,"AI, or artificial intelligence, is the ability...",[when actions are ambiguous or poorly controll...,2.897937,2.375597,5.314380,534,72,606,0.000080,0.000043,0.000123
1,How does AI differ from traditional programming?,Traditional programs follow fixed rules writte...,AI differs from traditional programming mainly...,[knowledge for a small educational chatbot or ...,0.901457,1.767215,2.671938,533,87,620,0.000080,0.000052,0.000132
2,What is Machine Learning?,Machine Learning is a branch of AI where compu...,Machine learning is a branch of artificial int...,[The relationship among the three concepts is ...,0.278740,1.527383,1.809496,394,58,452,0.000059,0.000035,0.000094
3,What is Deep Learning?,Deep Learning is a type of Machine Learning th...,Deep learning is a specialized area within mac...,[The relationship among the three concepts is ...,0.254192,1.455021,1.711368,447,47,494,0.000067,0.000028,0.000095
4,"What is the difference between AI, ML, and Dee...",AI is the broad field of making machines intel...,"The difference among AI, ML, and Deep Learning...",[The relationship among the three concepts is ...,0.261940,2.178629,2.443208,455,116,571,0.000068,0.000070,0.000138
5,What is training data?,Training data is the data used to teach a Mach...,Training data is the collection of examples us...,[AI TEACHING DATASET - PARAGRAPH DOCUMENTATION...,3.787196,1.888601,5.679920,489,72,561,0.000073,0.000043,0.000117
6,What is a Machine Learning model?,A Machine Learning model is a mathematical sys...,A machine learning model is the mathematical s...,"[recommendation, or decision. The model does n...",0.302687,1.308059,1.615325,461,67,528,0.000069,0.000040,0.000109
7,What is supervised learning?,Supervised learning trains a model using examp...,Supervised learning uses examples that contain...,"[recommendation, or decision. The model does n...",0.242720,1.562164,1.807614,406,64,470,0.000061,0.000038,0.000099
8,What is unsupervised learning?,Unsupervised learning works with data that doe...,Unsupervised learning works with information t...,"[recommendation, or decision. The model does n...",0.255543,1.258832,1.515654,408,70,478,0.000061,0.000042,0.000103
9,What is reinforcement learning?,Reinforcement learning teaches an agent throug...,Reinforcement learning teaches an agent throug...,"[model searches for hidden structures, similar...",0.251749,1.313140,1.566590,531,65,596,0.000080,0.000039,0.000119
10,What is an LLM?,"An LLM, or Large Language Model, is an AI mode...","An LLM, or large language model, is an AI mode...",[AI TEACHING DATASET - PARAGRAPH DOCUMENTATION...,0.243174,3.161038,3.408430,404,72,476,0.000061,0.000043,0.000104
11,What is Generative AI?,Generative AI is AI that can create new conten...,Generative AI is the broader category of artif...,[AI TEACHING DATASET - PARAGRAPH DOCUMENTATION...,0.335914,1.382655,1.720102,540,66,606,0.000081,0.000040,0.000121
12,What is a prompt?,A prompt is the instruction or input given to ...,A prompt is the instruction or input supplied ...,[These systems produce new combinations rather...,0.337776,1.990488,2.331361,420,61,481,0.000063,0.000037,0.000100
13,What is Prompt Engineering?,Prompt Engineering is the practice of designin...,Prompt engineering is the practice of designin...,[These systems produce new combinations rather...,0.342077,1.272389,1.617553,420,64,484,0.000063,0.000038,0.000101
14,What is RAG?,RAG stands for Retrieval-Augmented Generation....,"RAG, or retrieval-augmented generation, combin...",[because a prompt may be adjusted after review...,0.370647,1.451866,1.824728,429,75,504,0.000064,0.000045,0.000109
15,Why is RAG useful?,RAG is useful when an AI application needs to ...,RAG is useful because it combines information ...,"[response time, the application can be more gr...",0.228802,2.061077,2.292121,430,100,530,0.000064,0.000060,0.000124
16,What is a vector database?,A vector database stores numerical representat...,A vector database stores embeddings together w...,[AI TEACHING DATASET - PARAGRAPH DOCUMENTATION...,0.252347,1.337260,1.591846,482,34,516,0.000072,0.000020,0.000093
17,What are embeddings?,Embeddings are numerical representations of te...,Embeddings are numerical representations of te...,[AI TEACHING DATASET - PARAGRAPH DOCUMENTATION...,0.255201,1.721051,1.977631,589,76,665,0.000088,0.000046,0.000134
18,What is an AI Agent?,An AI Agent is a system that can understand a ...,An AI agent is a system that works toward a go...,[selected passages are then sent to the langua...,0.228689,1.785847,2.017067,536,118,654,0.000080,0.000071,0.000151
19,How can AI be used in education?,AI can support education by explaining concept...,AI can be used in education by explaining conc...,[when actions are ambiguous or poorly controll...,0.234996,1.363648,1.600861,538,71,609,0.000081,0.000043,0.000123

# STAGE 5 - LLM EVALUATION - ANSWER QUALITY

In [20]:
quality_scores = []

for _, row in tqdm(
    results_df.iterrows(),
    total=len(results_df),
    desc="Answer quality"
):
    query = row["User Query"]
    generated = row["GeneratedAnswer"]
    reference = row["Teacher Response"]

    if not generated:
        quality_scores.append([np.nan] * 3)
        continue

    test_case = LLMTestCase(
        input=query,
        actual_output=generated,
        expected_output=reference
    )

    scores = []

    for metric in [
        correctness_metric,
        answer_relevancy_metric,
        helpfulness_metric
    ]:
        try:
            metric.measure(test_case)
            scores.append(float(metric.score))
        except Exception as e:
            print(f"{metric.__class__.__name__} error: {e}")
            scores.append(np.nan)

    quality_scores.append(scores)


results_df[
    ["AnswerCorrectness", "AnswerRelevancy", "Helpfulness"]
] = pd.DataFrame(
    quality_scores,
    index=results_df.index
)

results_df["AnswerQuality"] = results_df[
    ["AnswerCorrectness", "AnswerRelevancy", "Helpfulness"]
].mean(axis=1)

display(results_df[
    [
        "User Query",
        "AnswerCorrectness",
        "AnswerRelevancy",
        "Helpfulness",
        "AnswerQuality"
    ]
])

Answer quality:   0%|          | 0/20 [00:00<?, ?it/s]

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

,User Query,AnswerCorrectness,AnswerRelevancy,Helpfulness,AnswerQuality
0,What is AI?,0.900000,1.000000,1.000000,0.966667
1,How does AI differ from traditional programming?,0.911280,1.000000,1.000000,0.970427
2,What is Machine Learning?,0.920689,1.000000,1.000000,0.973563
3,What is Deep Learning?,0.912252,1.000000,0.908756,0.940336
4,"What is the difference between AI, ML, and Dee...",1.000000,1.000000,0.902596,0.967532
5,What is training data?,0.803210,1.000000,0.980317,0.927842
6,What is a Machine Learning model?,0.904209,1.000000,1.000000,0.968070
7,What is supervised learning?,0.993245,1.000000,1.000000,0.997748
8,What is unsupervised learning?,0.980317,1.000000,0.992630,0.990983
9,What is reinforcement learning?,0.908270,1.000000,1.000000,0.969423
10,What is an LLM?,0.902229,1.000000,0.953898,0.952042
11,What is Generative AI?,0.918243,1.000000,0.994967,0.971070
12,What is a prompt?,0.832082,1.000000,1.000000,0.944027
13,What is Prompt Engineering?,0.789912,1.000000,1.000000,0.929971
14,What is RAG?,0.949219,1.000000,1.000000,0.983073
15,Why is RAG useful?,0.900000,1.000000,0.959267,0.953089
16,What is a vector database?,0.897967,1.000000,0.902844,0.933603
17,What are embeddings?,0.931405,1.000000,0.990731,0.974045
18,What is an AI Agent?,0.893046,0.666667,0.900000,0.819904
19,How can AI be used in education?,0.896691,1.000000,1.000000,0.965564

# STAGE 6 - EVALUATE SIMILARITY METRICS

In [18]:
similarity_scores = []

for _, row in tqdm(
    results_df.iterrows(),
    total=len(results_df),
    desc="Similarity metrics"
):
    reference = row["Teacher Response"]
    generated = row["GeneratedAnswer"]

    if not generated:
        similarity_scores.append([np.nan] * 5)
        continue

    try:
        _, _, f1 = bert_scorer.score(
            [generated],
            [reference]
        )
        bert = float(f1[0])
    except Exception:
        bert = np.nan

    try:
        rouge_scores = rouge.score(reference, generated)

        rouge1 = rouge_scores["rouge1"].fmeasure
        rouge2 = rouge_scores["rouge2"].fmeasure
        rougeL = rouge_scores["rougeL"].fmeasure
    except Exception:
        rouge1 = rouge2 = rougeL = np.nan

    try:
        meteor = meteor_score(
            [reference.split()],
            generated.split()
        )
    except Exception:
        meteor = np.nan

    similarity_scores.append([
        bert, rouge1, rouge2, rougeL, meteor
    ])


similarity_columns = [
    "BERT",
    "ROUGE-1",
    "ROUGE-2",
    "ROUGE-L",
    "METEOR"
]

results_df[similarity_columns] = pd.DataFrame(
    similarity_scores,
    index=results_df.index
)

display(results_df[["User Query"] + similarity_columns])

Similarity metrics:   0%|          | 0/20 [00:00<?, ?it/s]

,User Query,BERT,ROUGE-1,ROUGE-2,ROUGE-L,METEOR
0,What is AI?,0.936465,0.541176,0.385542,0.494118,0.697060
1,How does AI differ from traditional programming?,0.896392,0.326923,0.196078,0.288462,0.466625
2,What is Machine Learning?,0.909317,0.444444,0.278481,0.444444,0.457683
3,What is Deep Learning?,0.941287,0.606061,0.468750,0.606061,0.739874
4,"What is the difference between AI, ML, and Dee...",0.913300,0.597701,0.352941,0.528736,0.558382
5,What is training data?,0.895691,0.391304,0.200000,0.347826,0.465113
6,What is a Machine Learning model?,0.900434,0.450000,0.153846,0.300000,0.442387
7,What is supervised learning?,0.913420,0.457831,0.172840,0.337349,0.484613
8,What is unsupervised learning?,0.928887,0.439024,0.175000,0.365854,0.503774
9,What is reinforcement learning?,0.926493,0.453333,0.219178,0.346667,0.616099
10,What is an LLM?,0.928610,0.463415,0.375000,0.463415,0.661765
11,What is Generative AI?,0.928781,0.506329,0.337662,0.354430,0.652339
12,What is a prompt?,0.894222,0.309524,0.219512,0.309524,0.302452
13,What is Prompt Engineering?,0.898368,0.373333,0.191781,0.320000,0.330066
14,What is RAG?,0.882056,0.320755,0.057692,0.207547,0.318922
15,Why is RAG useful?,0.890942,0.267857,0.090909,0.214286,0.399352
16,What is a vector database?,0.909498,0.440000,0.166667,0.360000,0.395426
17,What are embeddings?,0.913433,0.373626,0.269663,0.351648,0.479962
18,What is an AI Agent?,0.897887,0.356589,0.188976,0.279070,0.396828
19,How can AI be used in education?,0.932310,0.488372,0.285714,0.441860,0.649441

# STAGE 7 - RAG EVALUATION METRICS

In [19]:
async def calculate_ragas(query, reference, generated):
    try:
        score = await answer_correctness_metric.ascore(
            user_input=query,
            response=generated,
            reference=reference
        )
        return float(score.value)
    except Exception as e:
        print("RAGAS error:", e)
        return np.nan


rag_scores = []

for _, row in tqdm(
    results_df.iterrows(),
    total=len(results_df),
    desc="RAG evaluation"
):
    query = row["User Query"]
    reference = row["Teacher Response"]
    generated = row["GeneratedAnswer"]
    context = row["RetrievedContext"]

    if not generated:
        rag_scores.append([np.nan] * 6)
        continue

    # RAGAS
    ragas_score = await calculate_ragas(
        query, reference, generated
    )

    # DEEPEVAL RAG METRICS
    test_case = LLMTestCase(
        input=query,
        actual_output=generated,
        expected_output=reference,
        retrieval_context=context
    )

    metric_values = []

    for metric in [
        context_precision_metric,
        context_recall_metric,
        faithfulness_metric,
        rag_answer_relevancy_metric,
        rag_geval_metric
    ]:
        try:
            metric.measure(test_case)
            metric_values.append(float(metric.score))
        except Exception as e:
            print(f"{metric.__class__.__name__} error: {e}")
            metric_values.append(np.nan)

    # Order: RAGAS, precision, recall, faithfulness,
    # answer relevancy, GEval
    rag_scores.append([
        ragas_score,
        *metric_values
    ])


rag_columns = [
    "Ragas AnswerCorrectness",
    "Context Precision",
    "Context Recall",
    "Faithfulness",
    "RAG Answer Relevancy",
    "RAG GEval"
]

results_df[rag_columns] = pd.DataFrame(
    rag_scores,
    index=results_df.index
)

results_df["RAG Evaluation Score"] = results_df[
    rag_columns
].mean(axis=1)

display(results_df[["User Query"] + rag_columns + [
    "RAG Evaluation Score"
]])

RAG evaluation:   0%|          | 0/20 [00:00<?, ?it/s]

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

FaithfulnessMetric error: RetryError[<Future at 0x2158ac2d110 state=finished raised TimeoutError>]

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

,User Query,Ragas AnswerCorrectness,Context Precision,Context Recall,Faithfulness,RAG Answer Relevancy,RAG GEval,RAG Evaluation Score
0,What is AI?,0.979948,0.5,1.0,1.0,1.0,0.8,0.879991
1,How does AI differ from traditional programming?,0.928222,1.0,1.0,1.0,1.0,0.9,0.971370
2,What is Machine Learning?,0.678200,1.0,1.0,1.0,1.0,0.7,0.896367
3,What is Deep Learning?,0.796950,1.0,1.0,1.0,1.0,0.7,0.916158
4,"What is the difference between AI, ML, and Dee...",0.948836,1.0,1.0,1.0,1.0,0.9,0.974806
5,What is training data?,0.554960,1.0,1.0,1.0,1.0,0.7,0.875827
6,What is a Machine Learning model?,0.548598,1.0,1.0,1.0,1.0,1.0,0.924766
7,What is supervised learning?,0.647569,1.0,1.0,1.0,1.0,0.9,0.924595
8,What is unsupervised learning?,0.715114,1.0,1.0,1.0,1.0,0.7,0.902519
9,What is reinforcement learning?,0.547397,1.0,1.0,1.0,1.0,0.4,0.824566
10,What is an LLM?,0.515585,1.0,1.0,1.0,0.9,0.8,0.869264
11,What is Generative AI?,0.726595,1.0,1.0,1.0,1.0,0.3,0.837766
12,What is a prompt?,0.499478,1.0,1.0,NaN,1.0,0.9,0.879896
13,What is Prompt Engineering?,0.441748,1.0,1.0,1.0,1.0,0.6,0.840291
14,What is RAG?,0.902936,1.0,1.0,1.0,1.0,0.9,0.967156
15,Why is RAG useful?,0.323776,1.0,1.0,1.0,1.0,0.9,0.870629
16,What is a vector database?,0.866333,1.0,1.0,1.0,1.0,0.9,0.961055
17,What are embeddings?,0.587289,1.0,1.0,1.0,1.0,0.8,0.897881
18,What is an AI Agent?,0.641501,1.0,1.0,1.0,1.0,0.6,0.873583
19,How can AI be used in education?,0.976722,1.0,1.0,1.0,1.0,0.6,0.929454

# STAGE 8 - OPERATIONAL METRICS SUMMARY

In [21]:
operational_columns = [
    "RetrievalLatency",
    "GenerationLatency",
    "Latency",
    "InputTokens",
    "OutputTokens",
    "TotalTokens",
    "InputCost",
    "OutputCost",
    "TotalCost"
]

operational_summary = pd.DataFrame({
    "Metric": operational_columns,
    "Average": [
        results_df[c].mean() for c in operational_columns
    ],
    "Total": [
        results_df[c].sum() for c in operational_columns
    ]
})

display(operational_summary.round(6))

              Metric     Average         Total
0   RetrievalLatency    0.398306      7.966110
1  GenerationLatency    1.590429     31.808588
2            Latency    1.991659     39.833170
3        InputTokens  472.300000   9446.000000
4       OutputTokens   71.250000   1425.000000
5        TotalTokens  543.550000  10871.000000
6          InputCost    0.000071      0.001417
7         OutputCost    0.000043      0.000855
8          TotalCost    0.000114      0.002272

# STAGE 9 - FINAL EVALUATION TABLE SUMMARY

In [22]:
# ROUND ALL METRIC COLUMNS

metric_columns = [
    "AnswerCorrectness",
    "AnswerRelevancy",
    "Helpfulness",
    "AnswerQuality",
    *similarity_columns,
    *rag_columns,
    "RAG Evaluation Score"
]

results_df[metric_columns] = results_df[metric_columns].round(3)


# FINAL QUESTION-WISE TABLE

final_columns = [
    "User Query",
    "Teacher Response",
    "GeneratedAnswer",
    *metric_columns,
    *operational_columns
]

final_df = results_df[final_columns].copy()

display(final_df)


# AVERAGE EVALUATION SUMMARY

summary_df = pd.DataFrame({
    "Metric": metric_columns,
    "Average Score": [
        results_df[c].mean() for c in metric_columns
    ]
})

summary_df["Average Score"] = (
    summary_df["Average Score"].round(3)
)

display(summary_df)


# SAVE OUTPUTS

final_df.to_csv(
    OUTPUT_CSV,
    index=False,
    encoding="utf-8-sig"
)

summary_df.to_csv(
    "RAG_LLM_EVALUATION_SUMMARY.csv",
    index=False,
    encoding="utf-8-sig"
)

operational_summary.to_csv(
    "RAG_LLM_OPERATIONAL_SUMMARY.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Evaluation completed.")
print("Final results:", OUTPUT_CSV)
print("Evaluation summary: RAG_LLM_EVALUATION_SUMMARY.csv")
print("Operational summary: RAG_LLM_OPERATIONAL_SUMMARY.csv")

,User Query,Teacher Response,GeneratedAnswer,AnswerCorrectness,AnswerRelevancy,Helpfulness,AnswerQuality,BERT,ROUGE-1,ROUGE-2,...,RAG Evaluation Score,RetrievalLatency,GenerationLatency,Latency,InputTokens,OutputTokens,TotalTokens,InputCost,OutputCost,TotalCost
0,What is AI?,AI (Artificial Intelligence) is the ability of...,"AI, or artificial intelligence, is the ability...",0.900,1.000,1.000,0.967,0.936,0.541,0.386,...,0.880,1.441383,3.536660,4.990236,534,72,606,0.000080,0.000043,0.000123
1,How does AI differ from traditional programming?,Traditional programs follow fixed rules writte...,AI differs from traditional programming mainly...,0.911,1.000,1.000,0.970,0.896,0.327,0.196,...,0.971,0.718855,1.794741,2.514886,533,87,620,0.000080,0.000052,0.000132
2,What is Machine Learning?,Machine Learning is a branch of AI where compu...,Machine learning is a branch of artificial int...,0.921,1.000,1.000,0.974,0.909,0.444,0.278,...,0.896,0.257677,1.422330,1.681944,394,58,452,0.000059,0.000035,0.000094
3,What is Deep Learning?,Deep Learning is a type of Machine Learning th...,Deep learning is a specialized area within mac...,0.912,1.000,0.909,0.940,0.941,0.606,0.469,...,0.916,0.241056,1.090079,1.332338,447,47,494,0.000067,0.000028,0.000095
4,"What is the difference between AI, ML, and Dee...",AI is the broad field of making machines intel...,"The difference among AI, ML, and Deep Learning...",1.000,1.000,0.903,0.968,0.913,0.598,0.353,...,0.975,0.382961,1.331282,1.716430,455,64,519,0.000068,0.000038,0.000107
5,What is training data?,Training data is the data used to teach a Mach...,Training data is the collection of examples us...,0.803,1.000,0.980,0.928,0.896,0.391,0.200,...,0.876,0.300669,1.430209,1.733045,489,72,561,0.000073,0.000043,0.000117
6,What is a Machine Learning model?,A Machine Learning model is a mathematical sys...,A machine learning model is the mathematical s...,0.904,1.000,1.000,0.968,0.900,0.450,0.154,...,0.925,0.306214,1.535233,1.843204,461,67,528,0.000069,0.000040,0.000109
7,What is supervised learning?,Supervised learning trains a model using examp...,Supervised learning uses examples that contain...,0.993,1.000,1.000,0.998,0.913,0.458,0.173,...,0.925,0.303528,1.226223,1.532739,406,64,470,0.000061,0.000038,0.000099
8,What is unsupervised learning?,Unsupervised learning works with data that doe...,Unsupervised learning works with information t...,0.980,1.000,0.993,0.991,0.929,0.439,0.175,...,0.903,0.306153,1.324377,1.632719,408,70,478,0.000061,0.000042,0.000103
9,What is reinforcement learning?,Reinforcement learning teaches an agent throug...,Reinforcement learning teaches an agent throug...,0.908,1.000,1.000,0.969,0.926,0.453,0.219,...,0.825,0.305573,1.634641,1.942518,531,66,597,0.000080,0.000040,0.000119
10,What is an LLM?,"An LLM, or Large Language Model, is an AI mode...","An LLM, or large language model, is an AI mode...",0.902,1.000,0.954,0.952,0.929,0.463,0.375,...,0.869,0.305720,1.283193,1.591308,404,72,476,0.000061,0.000043,0.000104
11,What is Generative AI?,Generative AI is AI that can create new conten...,Generative AI is the broader category of artif...,0.918,1.000,0.995,0.971,0.929,0.506,0.338,...,0.838,0.348582,1.940452,2.292595,540,66,606,0.000081,0.000040,0.000121
12,What is a prompt?,A prompt is the instruction or input given to ...,A prompt is the instruction or input supplied ...,0.832,1.000,1.000,0.944,0.894,0.310,0.220,...,0.880,0.320889,1.123247,1.446278,420,61,481,0.000063,0.000037,0.000100
13,What is Prompt Engineering?,Prompt Engineering is the practice of designin...,Prompt engineering is the practice of designin...,0.790,1.000,1.000,0.930,0.898,0.373,0.192,...,0.840,0.394375,1.234169,1.631851,420,64,484,0.000063,0.000038,0.000101
14,What is RAG?,RAG stands for Retrieval-Augmented Generation....,"RAG, or retrieval-augmented generation, combin...",0.949,1.000,1.000,0.983,0.882,0.321,0.058,...,0.967,0.294059,1.533777,1.830298,429,95,524,0.000064,0.000057,0.000121
15,Why is RAG useful?,RAG is useful when an AI application needs to ...,RAG is useful because it combines information ...,0.900,1.000,0.959,0.953,0.891,0.268,0.091,...,0.871,0.304587,1.941857,2.249000,430,101,531,0.000064,0.000061,0.000125
16,What is a vector database?,A vector database stores numerical representat...,A vector database stores embeddings together w...,0.898,1.000,0.903,0.934,0.909,0.440,0.167,...,0.961,0.308191,1.122391,1.433458,482,34,516,0.000072,0.000020,0.000093
17,What are embeddings?,Embeddings are numerical representations of te...,Embeddings are numerical representations of te...,0.931,1.000,0.991,0.974,0.913,0.374,0.270,...,0.898,0.308663,1.733412,2.045103,589,76,665,0.000088,0.000046,0.000134
18,What is an AI Agent?,An AI Agent is a system that can understand a ...,An AI agent is a system that works toward a go...,0.893,0.667,0.900,0.820,0.898,0.357,0.189,...,0.874,0.303603,2.150873,2.456722,536,118,654,0.000080,0.000071,0.000151
19,How can AI be used in education?,AI can support education by explaining concept...,AI can be used in education by explaining conc...,0.897,1.000,1.000,0.966,0.932,0.488,0.286,...,0.929,0.513372,1.419443,1.936499,538,71,609,0.000081,0.000043,0.000123

                     Metric  Average Score
0         AnswerCorrectness          0.907
1           AnswerRelevancy          0.983
2               Helpfulness          0.974
3             AnswerQuality          0.955
4                      BERT          0.912
5                   ROUGE-1          0.430
6                   ROUGE-2          0.239
7                   ROUGE-L          0.368
8                    METEOR          0.501
9   Ragas AnswerCorrectness          0.691
10        Context Precision          0.975
11           Context Recall          1.000
12             Faithfulness          1.000
13     RAG Answer Relevancy          0.995
14                RAG GEval          0.750
15     RAG Evaluation Score          0.901

Evaluation completed.
Final results: RAG_LLM_FINAL_EVALUATION.csv
Evaluation summary: RAG_LLM_EVALUATION_SUMMARY.csv
Operational summary: RAG_LLM_OPERATIONAL_SUMMARY.csv